### ISSUE TITLE
Not recognizing Pluto 1.0.1R Servo Drives

### ISSUE THREAD

**Issue by AidanNelson** [ingeniamc/ingenialink-python#2]
Hello!  

I am having trouble getting this library to recognize a Pluto Servo Driver (1.0.1R).  I have installed this library on two machines using `pip install ingenialink`, one Mac OS X (10.11.6 El Capitan) and a Raspberry Pi (Raspian Stretch Lite).  In both cases, I am able to... 

1. import ingenialink module in python, 
2. recognize the correct USB device (using `il.devices` method),
3. and create a `il.Network` object for that USB device.

At this point, however, **running net.Servos() returns an empty list**, despite a Pluto Servo Drive being connected. 

After reading through some of the documentation here, and on the ingenialink C library [here](https://github.com/ingeniamc/ingenialink), I suspected that the sercomm dependency library was missing, as I was not able to see any file name including sercomm in the ingenialink-python package folder.  So I tried to build the python library using `python setup.py build` and `python setup.py install`.  This has not produced a running install, but may be due to my having multiple homebrew python versions installed.

Any advice or guidance on setting up this install would go a long way!

Thanks!

**Comment by gmarull** [comment]
Hi Aidan,

`libsercomm` is automatically downloaded, compiled and embedded into the Python extension, so I don't think it is the source of the problem. Furthermore, `il.devices()` uses `libsercomm`, and you say it is working. If the problem happens in both macOS and RPi, my guess is that the problem comes from the firmware side.

Which firmware version are you using?
Are you connected to the board using its USB port?
Is the board powered using an external power supply?

Thanks!

**Comment by AidanNelson** [comment]
Hi Gerard,

Yes, the board is connected with its USB port and powered using an external power supply.  The firmware was an older version (1.1.8).  I updated it through MotionLab (running on a virtual machine on Mac OS X) to FW version 2.5.2, and it is now being recognized by python ingenialink.  Great!  

Unfortunately, MotionLab will no longer enter into drive configuration for this drive.  Instead, when I click on the Pluto from the Detected Drives screen, a dialog box 

> "Reading parameters from drive..." 

appears as usual, but is replaced after 5 seconds with another dialog box 

>"Searching for drives in the computer..."

such that I cannot enter the drive configuration screen.

Any idea what might be causing this? 

Thanks,
Aidan

**Comment by gmarull** [comment]
If I'm not wrong old firmwares did not implement the "binary protocol" required by IngeniaLink, so that was probably the error. I will try to find out in which version it was introduced and update the docs. 

We had issues using MotionLab running on top of VM because they way MotionLab handles communications, so this is probably the issue now. Can you try using a native Windows machine?

**Comment by AidanNelson** [comment]
Yes, I will try using MotionLab on a native Windows machine. 

In the meantime, I tried downgrading the Pluto to firmware version 2.4.3 to see if it might communicate with MotionLab on the older FW, which it did not.  Then I downgraded further to FW 2.3.1, which seems to communicate ok with MotionLab in my setup.

**Comment by gmarull** [comment]
Are you using the latest version of MotionLab? We always suggest using the latest firmware, as any issues you can find may be already fixed. Anyway, if that works for you keep going on. If you find no further problems when using a native Windows machine we shall proceed to close this issue.

Regards,
